### ISSUE TITLE
Multiprocessing tiles degrades over time

### ISSUE THREAD

**Issue by gjn** [geoadmin/3d-forge#102]
Still creating level 18 -> `[23758] It took 9:48:47.510446 to create 377420 tiles on S3.`

But I observed that processes simply stop working after some time (I think it was after 4 hours this time). Then there were 7, then 6, then 5....no not a single process is busy, no error message at all, and in theory, still quite a few tiles should be calculated.

Something is still fishy.

**Comment by loicgasser** [comment]
We probably need to introduce queing and check when a process completes a task/if the process is still alive.

I would also like to know the maximal number of objects that were created for a tile if you can find it in the logs.

We could also use a python profiler.

**Comment by gjn** [comment]
I've aborted the level 18 after `[23758] It took 9:48:47.510446 to create 377420 tiles on S3.` Around 40K tiles were skipped. So total over 410K were handled. But almost 800K should have been treated.

**Comment by gjn** [comment]
I thinks it's not only a problem with lazy iterating. This doesn't explain that it stopped yesterday 18:00 to create tiles, while not even half of them were processed. All processes were still running, but nothing was happening for hours.
