### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by homme** [geoadmin/3d-forge#166]
Hello - I'm looking at your code in relation to [this issue](https://github.com/geo-data/cesium-terrain-builder/issues/29) and I'm just wondering what license you're making 3d-forge code available under?

**Comment by loicgasser** [comment]
Hi, under MIT.
lib encoder/decoder and topology builder have been separated here:
https://github.com/loicgasser/quantized-mesh-tile

I haven't had the time to finish and document it as I d like yet.

**Comment by homme** [comment]
That's very helpful, thanks very much!
