### ISSUE TITLE
Scripts outside ipython

### ISSUE THREAD

**Issue by gjn** [geoadmin/3d-forge#17]
Can we make our scripts runnable outside ipython?

tms_polygons.py only works inside ipython, which is not perfect for integrating such scripts in other processes.

**Comment by loicgasser** [comment]
Weird, are you sure? I don't know why this should be the case.. Do you use the python in venv?

**Comment by gjn** [comment]
(venv)ltjeg@ip-10-220-4-46 (vpc/mf0 - test):~/3d-forge$ python ./forge/scripts/tms_polygons.py
Extent :
[5.140299281276787, 45.39812174378221, 11.477436823766045, 48.23061646466064]
ERROR 1: 3.shp is not a directory.

Traceback (most recent call last):
  File "./forge/scripts/tms_polygons.py", line 44, in <module>
    layer = dataSource.CreateLayer('%s' % tz, srs, ogr.wkbPolygon)
AttributeError: 'NoneType' object has no attribute 'CreateLayer'

**Comment by gjn** [comment]
It would also be nice to put results in separate directory and only .gitignore this directory.

**Comment by loicgasser** [comment]
because you probably already have 3.shp ...

**Comment by gjn** [comment]
Indeed, deleting old results help...i would put them in separate directory.

**Comment by loicgasser** [comment]
yes, didn't have time yesterday, kind of did it on a rush, it's probably a one time script only.
