### ISSUE TITLE
Create Global Geodetic Tiler for shapefile triangles

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/3d-forge#37]
Based on a polygon layer containing a bunch of triangles in 2.5D, I believe we could create a tiler with a minimum of efforts.
It would ensure proper tiling as it is very important that the vertices and segments on the edges of the tile are shared with those of the neighbouring tiles.

After clipping, we would simply need to find the polgons with 4 points remove them and replace them with 2 triangles.
Using the exiting code that can be found in forge/script/tms_polygons.py, ogr GDAL clipping abilities (I would venture to say faster than shapely) http://www.gdal.org/classOGRLayer.html#a56d7ee3b2020e53c730d67ee4f1e2fb6
and the small algo described above, it might just do the trick.
We might need to split the different shapefiles because of probable memory issues (Alternatively store it in postgres).

It would also give us the flexibility to change/test the LODs at different zoom levels without having to wait for the tiles delivery, which I believe is not sorted out on their side.
@gjn @cedricmoullet some thoughts?

**Comment by gjn** [comment]
As discussed, let's spend 2 days on this and then let's review.

**Comment by loicgasser** [comment]
https://github.com/geoadmin/3d-forge/pull/39
