### ISSUE TITLE
Add water mask support in TerrainTile

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/3d-forge#53]

**Comment by cedricmoullet** [comment]
What is this ?

**Comment by loicgasser** [comment]
It is used to represent the presence of lakes in a tile. It is optional in quantized mesh format, but I think we should eventually implement it.

**Comment by loicgasser** [comment]
@gjn @ltclm 

The water mask included in a terrain data, if any. A water mask is a rectangular Uint8Array or image where a value of 255 indicates water and a value of 0 indicates land. Values in between 0 and 255 are allowed as well to smoothly blend between land and water.

So if we have polygons for the lakes, we can include it in the terrain data. We basically need to split the tile in 256x256 (so 65'536 operations) little squares and look for the presence of water in each square if we have a mix between land and water,  otherwise it's straightforward and pretty easy to implement.

So this will impact performance for tiles where we have a mix of land and water only. Good news is that according to my understanding, this will not impact the way we create the tile at the moment, it is "just" an addition.

**Comment by ltclm** [comment]
Hello Loic
I have prepared a pr providing a sql function for the watermask generation.
